// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XOyDqMR1e2N3MK0KHekNrPA3lYd_Oto',
    appId: '1:281258103315:android:0f7974afd5325ad811a5e6',
    messagingSenderId: '281258103315',
    projectId: 'chat-app-decc9',
    storageBucket: 'chat-app-decc9.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcWJxazp30Rvu33Xqv5XLc6al_wtMxIH8',
    appId: '1:281258103315:web:e24df2fa7e5eace111a5e6',
    messagingSenderId: '281258103315',
    projectId: 'chat-app-decc9',
    authDomain: 'chat-app-decc9.firebaseapp.com',
    storageBucket: 'chat-app-decc9.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcc9ER039AAFsQZ2mN0rmplE1rPBfSHU',
    appId: '1:281258103315:ios:2e3c7d5735262ca111a5e6',
    messagingSenderId: '281258103315',
    projectId: 'chat-app-decc9',
    storageBucket: 'chat-app-decc9.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcc9ER039AAFsQZ2mN0rmplE1rPBfSHU',
    appId: '1:281258103315:ios:2e3c7d5735262ca111a5e6',
    messagingSenderId: '281258103315',
    projectId: 'chat-app-decc9',
    storageBucket: 'chat-app-decc9.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcWJxazp30Rvu33Xqv5XLc6al_wtMxIH8',
    appId: '1:281258103315:web:79c2264085e8f51111a5e6',
    messagingSenderId: '281258103315',
    projectId: 'chat-app-decc9',
    authDomain: 'chat-app-decc9.firebaseapp.com',
    storageBucket: 'chat-app-decc9.appspot.com',
  );

}